name: Build

on: [push, pull_request]

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install pipenv
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: pipenv
      - run: pipenv install --dev
      - run: pipenv run check
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
      - run: npm ci
      - run: npm run lint
